### PR TITLE
Full rewrite

### PR DESCRIPTION
**Pull request by Akianonymus**
flags: Add more documentation

[FEATURE] Support for sub-folders with --create-dir flag. | Resolve https://github.com/labbots/google-drive-upload/issues/155

install.sh: Do not fail if username is in small case

[SKIP-CI] Fix some shellcheck warinings

Use grep for -ex and -in flag | Resolve https://github.com/labbots/google-drive-upload/issues/176

Full rewrite

use a improved argument parser

add a -- flag, to treat all input as file or folder or drive id input

stop using set -e anywhere

add a improved config parser

fix all edgecases in authentication

commonize more code as possible

move update code to update.sh

do not edit zshrc or bashrc with the install script, instead show a help text on what to add to the zshrc or bashrc

move all files to src folder and release scripts in release folder

fix all shellcheck warnings

resolve https://github.com/labbots/google-drive-upload/issues/174 https://github.com/labbots/google-drive-upload/issues/176

### CODE REVIEW

**Comment by Akianonymus** [comment]
@labbots This is ready to merge. Github actions is failing because a new release has not been created.

**Review by labbots — APPROVED** [review]

**Comment by JorgeLNJunior** [comment]
I'm getting this error when trying to install.

```
curl --compressed -Ls https://github.com/Akianonymus/google-drive-upload/raw/master/install.sh | sh -s
---------------------------------------------------------------[ Installing google-drive-upload.. ]----------------------------------------------------------------
---------------------------------------------------------------------[ Downloading scripts.. ]---------------------------------------------------------------------
----------------------------------------------------------------------------[ gupload ]----------------------------------------------------------------------------
bash: line 7: syntax error near unexpected token `newline'
Script downloaded but malformed, try again and if the issue persists open an issue on github.
```

**Comment by Akianonymus** [comment]
> I'm getting this error when trying to install.
> 
> ```
> curl --compressed -Ls https://github.com/Akianonymus/google-drive-upload/raw/master/install.sh | sh -s
> ---------------------------------------------------------------[ Installing google-drive-upload.. ]----------------------------------------------------------------
> ---------------------------------------------------------------------[ Downloading scripts.. ]---------------------------------------------------------------------
> ----------------------------------------------------------------------------[ gupload ]----------------------------------------------------------------------------
> bash: line 7: syntax error near unexpected token `newline'
> Script downloaded but malformed, try again and if the issue persists open an issue on github.
> ```

Will be fixed after a new release has been created.

**Comment by Akianonymus** [comment]
@labbots Approve again.

**Comment by mdawart** [comment]
After updating to the new version, I always get an error 
```
michael@MacBook-Pro-von-Michael ~ % gupload --info
bash: _check_refresh_token: line 57: syntax error near unexpected token `&'
bash: _check_refresh_token: line 57: ` & _tmp_server_pid="$!";'
bash: error importing function definition for `_check_refresh_token'
REPO: labbots/google-drive-upload
INSTALL_PATH: /Users/michael/.google-drive-upload/bin
INSTALLATION: sh
TYPE: release
TYPE_VALUE: latest
LATEST_INSTALLED_SHA: e73d741c5480cd71edceeea54fa9b1d9374ebc45
```
I also tried to uninstall / reinstall but same result :-(

**Comment by Akianonymus** [comment]
That is a very weird error. You are on mac os, right ? Assuming your bash version is less than 4 and posix script was installed but it is trying to run the script with bash.

can you upload you gupload binary file and send me ? also, try upgrading your bash and reinstall again.

**Comment by mdawart** [comment]
[bin.tar.gz](https://github.com/labbots/google-drive-upload/files/9126215/bin.tar.gz)

checking my bash version 
```
michael@MacBook-Pro-von-Michael bin % bash -c 'echo $BASH_VERSION'
3.2.57(1)-release
```

when I run the uninstaller, I got this output
```
[ Uninstalling.. ]
chmod: --: No such file or directory
[  Remove below line from your shell rc manually  ]

[  Shell rc: /Users/michael/.zshrc  ]

[ -f "${HOME}/.google-drive-upload/bin/gupload" ] && [ -x "${HOME}/.google-drive-upload/bin" ] && PATH="${HOME}/.google-drive-upload/bin:${PATH}"

[ Uninstall complete. ]
```

needed to removed the .google-drive-upload manually and removed the addition from /Users/michael/.zshrc manually as described. 

Reinstalled using the script, same error.

**Pull request merged**
