### PR TITLE
Add support to overwrite files - Fix #14 | Fix parallel uploads for subdirs | Add check for empty directories | Many more stuff...

### LINKED ISSUE #14: overwrite previous files
Hello, thank you for the script works great.

I have a question though if uploading the same file but with updated content, how to make it overwrite the previously uploaded one instead of having the google drive create another one ?

### PR DESCRIPTION
**Pull request by Akianonymus**

### CODE REVIEW

**Comment by Akianonymus** [comment]
Need to check for possible bugs introduced..

**Comment by Akianonymus** [comment]
* Add check for empty directories.
* Add more logging.
* Tweak root folder checking output.

**Comment by labbots** [comment]
@Akianonymus could you please resolve the merge conflicts in the PR

**Comment by Akianonymus** [comment]
Refactor Script | Fix #14

upload.sh

    * Improve argument detection.
    
        * Allow giving arguments(file/folder) after/before the flags.
        
    * Parse longoptions properly ( Yay, without eval ).
    
    * Run respective flags argument checks early for share and parallel.
    
    * Store input arguments in an array, loop over it later.
    
    * Use mktemp if available.
    
    * Add -f/--file/--folder flag ( see README ).
    
    * Add -o/--overwritr flag ( see README ).
    
    * Add 10 secs timeout to internet connection check.
    
    * Use an efficient way to get $COLUMNS size interactively.
    
    * Improve all of the functions.
    
    * Use --compressed flag for all curl requests.
    
    * Allow parallel uploading for subdirs.
    
    * Replace [ with [[, considerably faster and useful.
    
    * Use bash string manipulation wherever sustainable( decreasing the execution time ).
    
    * Remove some useless checks.
    
    * Add more comments to the code.
    
    * Use printf instead of date
    
    * Use pure bash to sleep.
    
    * Improve error handling.
    
    * Add check for empty folders.
    
google-oauth2.sh

    * similar changes

README.md
    * Update for new flags

**Comment by Akianonymus** [comment]
@labbots Done, be sure to check the new features and for possible bugs that may have been introduced..

**Comment by Akianonymus** [comment]
Do not merge, need to cleanup a bit.

**Comment by Akianonymus** [comment]
All Done.

**Comment by labbots** [comment]
Thanks @Akianonymus I will test the changes tonight and merge the PR.

**Comment by Akianonymus** [comment]
More follow up commits.

upload.sh: Fix default root folder setting | Fix script for non tty

    * More generic fixes
    * Fix processArguments function in case of empty folders
    * Fix -i/--save-info flag when using parallel uploading

**Comment by Akianonymus** [comment]
Update

Add -q/--quiet flag

**Comment by labbots** [comment]
@Akianonymus thanks for your contribution.

**Pull request merged**
