### PR TITLE
[upload|install].sh: Allow setting custom config file as default | Update config only if specified, for -r/--root-dir | Add editorconfig | Misc

### PR DESCRIPTION
**Pull request by Akianonymus**
* default config can be also configured during installation 

* add editorconfig for shfmt

* change function names to lowercase and add underscores

### CODE REVIEW

**Comment by labbots** [comment]
@Akianonymus why is the camel case functions now changed to snake case?

**Comment by Akianonymus** [comment]
I actually didn't want to do that, but recently had conversation with someone, and it seems logical

For viewablity purposes as i have said in the commit message

```
*sh: functions: change exampleFunction to example_function

camelCase fumctions are indeed beautiful, but only when there are two strings as the defining words, more than that, it is not properly visible, and worse even in non-color terminals

so to maintain readablity for future, do this

```

For example, this

letsTryThisInCamelCase

lets_try_this_in_snake_case

The first one is definitely more beautiful, but less readable.

This may seem a little far fetched and personally opinionated, but yeah nothing else 🙂.

**Comment by labbots** [comment]
@Akianonymus I am looking at defining some naming conventions for the project. I will post of the convention shortly. We can decide about the changes once that is done.

**Comment by Akianonymus** [comment]
@labbots Perfect, i will wait.

**Comment by labbots** [comment]
@Akianonymus Here is the naming conventions I thought would be useful to follow in the project to keep everything consistent. Please provide your feedback.

### Naming Conventions

#### Variables and Constants
* Variable names must be meaningful and self-documenting.
* Long variable names must be structured by underscores to improve legibility.
* Global variables and constants must be ALL CAPS with underscores. (eg., INPUT_FILE)
* local variables used within functions must be all lower case with underscores. (eg., post_data)
* Variable names can be alphanumeric with underscores. No special characters in variable names.
* Variables name must not start with number. 

#### Functions
* Each function must contain a introductory comment. The comment must contain function name, short description of the function and description of the arguments and list of global variables used and modified.
```shell
#######################################
# Create directory in Google drive.
# Globals:
#   ROOT_DIR
# Arguments:
#   folder name to be created, access token.
# Returns:
#   0 if directory created successfully, non-zero on error.
#######################################
```
* Function names must be all lower case with underscores to seperate words (snake case).
* Internal functions must start with underscore. (eg., _check_connection())
* Package functions must be seperated with :: (eg., gupload::create_directory())

### Reference
* https://google.github.io/styleguide/shellguide.html
* https://github.com/icy/bash-coding-style#function-names

**Comment by Akianonymus** [comment]
> @Akianonymus Here is the naming conventions I thought would be useful to follow in the project to keep everything consistent. Please provide your feedback.
> 
> ### Naming Conventions
> #### Variables and Constants ...............

Well, i agree.

Just didn't understand the last one, how to exactly seperate ? 

Also, i was thinking of moving standalone functions to a new file, say name `utils.sh`.

Functions like printCenter, updateConfig which are completely standalone and are not related the gdrive uploading.

Installation script will be changed to merge all the code in 1 file when it is being installed system wide on server.

This way, it will be easy to actually debug and will not increase the no of lines in a single script, which for example will be too much when appropriate usage comments are added.

So, these are my proposals.

Nonetheless, it seems like it will be multiple new commits, so i removed my last commit so this can be merged.

**Comment by labbots** [comment]
@Akianonymus look at https://google.github.io/styleguide/shellguide.html#s7.1-function-names oogle style guide for function naming convention. For now I don't think we have any package functions exposed from the script. So you don't have to worry about the package function naming. It is actually required if we intent to provide library functions for others to source the project for their use. Example https://github.com/fidian/ansi/blob/master/ansi.

**Comment by Akianonymus** [comment]
@labbots I see, well, i will be straightforward, i don't like the idea, although the usecase would be useful only we had like too many files.

This is only useful after we split the functions in a different file ( which is the library ) and the main file would be main library.

Then that convention can be fulfilled, although it does makes the code messier and difficult to write, which i surely don't support.

So,  it's a minus one for me, although whatever you say should be good.

**Comment by Akianonymus** [comment]
Also, this pr can be merged, create a new issue with the main convention message you sent here, so it can properly managed.

**Comment by labbots** [comment]
@Akianonymus I have already added the naming conventions to CONTRIBUTING.md. I don't think we need to worry about package function naming for now. I was actually thinking of creating a separate script that can be sourced by other projects. Something like a library class. But I am not intending to do it at the moment. This is more for a future case.

**Comment by Akianonymus** [comment]
I need approval for some things

1. Should i separate the functions ?

2. Follow the package conventions if above

**Comment by Akianonymus** [comment]
I need approval for some things

1. Should i separate the functions ?

2. Follow the package conventions if above

**Comment by labbots** [comment]
@Akianonymus I think it would be a good idea to split common function to separate file but I don't think we need to do the package naming convention for function for now. If it is confusing I could remove that from the naming conventions.

**Comment by labbots** [comment]
@Akianonymus I think we should focus on writing unit tests for the script before adding more functionality to the script. We need to decide on a good unit test framework for bash script.

**Comment by Akianonymus** [comment]
@labbots Ok, also what are internal functions, function inside a function ?

**Comment by Akianonymus** [comment]
@labbots So, i saw the unit test concept.

Well, it may be pretty helpful in other languages but I don't think we need one in bash.

It's basically a wrapper for checking if the value of the command/function equals something or not, no offense to the developers.

I can definitely write a small 10 line function which would do the same, so no need for extra dependency.

Also, that type of unit testing is done for static output, means we exactly know how the output is going to be.

This can be easily done all of it, even network requests, but for network requests to work we would need to setup proper authentication, otherwise there is no point in checking for an output.

Standalone functions without any network requests are fine.

**Comment by Akianonymus** [comment]
@labbots So, i saw the unit test concept.

Well, it may be pretty helpful in other languages but I don't think we need one in bash.

It's basically a wrapper for checking if the value of the command/function equals something or not, no offense to the developers.

I can definitely write a small 10 line function which would do the same, so no need for extra dependency.

Also, that type of unit testing is done for static output, means we exactly know how the output is going to be.

This can be easily done all of it, even network requests, but for network requests to work we would need to setup proper authentication, otherwise there is no point in checking for an output.

Standalone functions without any network requests are fine.

**Comment by labbots** [comment]
@Akianonymus At present all the functions in the script are internal. I was thinking of prefixing the functions with underscore to distinguish between variables and functions. So all the functions must be prefixed with underscores.
In regards to the test, I think you still misunderstand the need and purpose of unit tests. The tests are supposed to be written in such a way that it tests the functionality of the function rather than external dependencies. There can be few integration tests which would test external dependencies but those tests creates a tight coupling with external factors and makes the test slower. The following testing pyramid explains the hierarchy of tests in any programming language.

image

**Comment by Akianonymus** [comment]
@labbots Yes, i understood that only, my bad if i wasn't clear in my comment, just see this.

https://github.com/dylanaraps/pure-bash-bible/blob/master/test.sh

About seperating functions, i would only be able seperate upload.sh internal functions.

If i do with install.sh, it will create problems as the installation is standalone and we don't need user to actually download the repo.

So, should i seperate functions of upload.sh ?

**Pull request merged**
