### PR TITLE
Use drive api v3 | Parallel Uploading | Sub folder upload | Improve logging | Pass shellcheck | Migrate to getopts | Share file/folder options | Format code

### PR DESCRIPTION
**Pull request by Akianonymus**
upload.sh
    * Use drive api v3.
    * Sub folder upload ( heirarchially ).
    * Improve logging a lot.
    * Add 2 new commands:

            -D | --debug - Display script command trace.
            -V | --verbose-progress - Display detailed message and detailed upload progress.

    * Improve root folder checking.
    * Merge url_escape.sed contents.
    * Passes shellcheck now.
    * Format script using shmft.

            shfmt -ci  -sr -i 4 -bn -w *sh

    * Remove some useless checks

    README.md
    * Update accoding to changes.
    * Improve script.

    google-oauth2.sh
    * Use drive v3 api

### CODE REVIEW

**Comment by Akianonymus** [comment]
DNM, need to fix some typos.

**Comment by Akianonymus** [comment]
1. Fix https://github.com/labbots/google-drive-upload/issues/17

2. Again, some major improvements in logging system, here how it looks now.

Normal and Verbose file upload.

Screenshot_20200402-223230

Normal folder Upload.

Screenshot_20200402-223352

Verbose folder upload.

Screenshot_20200402-223445

3. Add a option to save file information of various files uploaded in recursive folder upload.

Use -i/--save-info <filename> to save info to filename

See above screenshots.

**Comment by Akianonymus** [comment]
Possible fix for https://github.com/labbots/google-drive-upload/issues/20

Implement parallel downloading | Add a option to skip sub folder generation.

* Use xargs for parallel downloading.
* Use a more efficient function for url encoding.
* camelCase functions.
* Use trap to remove temp files in case of abnormal script exit.
* Report if any upload fails.
* Use local variables in functions.
* Add some checks for flags.
* Improve jsonValue function.

**Comment by Akianonymus** [comment]
Add flag to share file | Use bash getopts | Fix https://github.com/labbots/google-drive-upload/issues/12                                                                                        * -S/--share to automaticall share the file publicly after uploading                                                            * Use bash getops
    * Use wc to count file size instead of stat                     * Add a check for internet connection                           * Fix #12 ( by using bash getops and using wc )
    * Improve extractID and jsonValue method

**Comment by labbots** [comment]
@Akianonymus Thanks for your improvements. It works well.

**Comment by labbots** [comment]
@Akianonymus I have now merged your changes. Thanks for your contribution.

**Comment by Akianonymus** [comment]
Moar fixes coming in the near future, glad i could help.

Also, any new ideas to implement ? 
Except those 2 issues ( will check them later ).

**Comment by labbots** [comment]
@Akianonymus The main thing that I am thinking of doing are

- Overwrite file with same filename
- Resumable upload for large files
- Separate script to download files from google drive.

Let me know if you have any good ideas too.

**Comment by labbots** [comment]
I was also thinking of creating some kind of sync script to keep files in a folder synced with google drive folder.

**Comment by Akianonymus** [comment]
> @Akianonymus The main thing that I am thinking of doing are
> 
> - Overwrite file with same filename
> - Resumable upload for large files
> - Separate script to download files from google drive.
> 
> Let me know if you have any good ideas too.
> 

I have already implemented overwriting files.

Resumable upload should be easy too.

For downloading files, i have a seperate repo on my git as gdrive-downloader( gotta update it, it's barebones, but works on folders and files both), could be imported here with some changes.

Although, i don't think it's a good idea to deviate from the idea that repo name gives.

**Comment by Akianonymus** [comment]
> I was also thinking of creating some kind of sync script to keep files in a folder synced with google drive folder.

Well, just gotta run ./upload.sh foldername

( after the overwriting feature ).

**Pull request merged**
