### PR TITLE
github-action: create basic-checks.yaml

### PR DESCRIPTION
**Pull request by icy**

### CODE REVIEW

**Comment by labbots** [comment]
@icy Thanks for your PR but we already have Codacy check enabled which does all the shellcheck for script and some coding standard for markdown files. The dashboard is available at https://app.codacy.com/manual/labbots/google-drive-upload/dashboard. So I believe the github actions for shellcheck is not necessary.

**Comment by icy** [comment]
Thanks @labbots . I didn't know how it's working so I sent the PR. It's clear now :)

**Comment by labbots** [comment]
Thanks once again for showing interest in the project @icy. I have read your [coding style documentation ](https://github.com/icy/bash-coding-style).  I was looking to implement them in this project. We have been having discussions about it in another [PR](https://github.com/labbots/google-drive-upload/pull/53). Any input and contributions to the project is very much welcomed.

**Comment by icy** [comment]
> Thanks once again for showing interest in the project @icy. I have read your [coding style documentation ](https://github.com/icy/bash-coding-style). I was looking to implement them in this project. We have been having discussions about it in another [PR](https://github.com/labbots/google-drive-upload/pull/53). Any input and contributions to the project is very much welcomed.

I'm happy that my work would help a bit. I'm always looking for a simple tool to synchronize (backup) my google drive files, and the first thing I can help the project is to be an user of of it :+1:

**Comment by icy** [comment]
I have a chance to use the tool today, to upload a huge archive of backup files to our company google drive . It works flawless :P though the setup/authentication/authorization process is quite painful, I have to visit google links and enter the code everytime. I would use this only once, so that's fine . Any hint to remove any current token would be useful (~/.googledrive.conf)

Thanks for the awesome tool

**Comment by labbots** [comment]
@icy I am happy that it worked well for you. I am not sure why it asks you to enter a code everytime. It is supposed to be one time setup. Once the refresh token is set on the googledrive.conf file then that token would be used for following uploads. Do you have multi factor authentication set on the account?. 
Regarding removing the tokens from the system, simply deleting the .googledrive.conf is sufficient. If you want to invalidate the token, you could delete the key from google console from where you initially generated the token. Hope that helps.

**Comment by Akianonymus** [comment]
Adding to labbots comment, you can save the refresh token and use it indefinitely, if you are working in a ci, just echo VALUES in .googledrive.conf

like `echo REFRESH_TOKEN=SOMETHING` >>  ~/.googledrive.conf`

Also, the Authorization process is same in all gdrive apps available out there, I don't if their is an easy way to authorize, will look into it.

**Pull request closed without merging**
