### PR TITLE
Add flag to limit speed | Add github action check for installation | Bugfixes | Misc

### PR DESCRIPTION
**Pull request by Akianonymus**

### CODE REVIEW

**Comment by Akianonymus** [comment]
Added github action check to avoid any future problems like #80

**Comment by Akianonymus** [comment]
btw, need to update repository settings to allow github actions


https://github.community/t/workflow-error-action-not-allowed/16788/2

**Comment by labbots** [comment]
I have enabled the actions and I hope it works from next push to master

**Comment by Akianonymus** [comment]
nice, btw, can you pick this commit, delete old release and tag and make a new one

https://github.com/Akianonymus/google-drive-upload/commit/3f0c8a5a0ae49e016c8d84a4f956e8fbba7e3090

i missed it for some reason :(, my bad.

**Pull request merged**
